server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/access?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
    mapper-locations: classpath:com/nancy/control/dao/*.xml
    mybatis.type-aliases-package: com.nancy.control.bean